<?php
require_once 'db.php';
require_once 'auth.php';
require_once 'fpdf/fpdf.php';

if (!isset($_GET['id'])) {
    die("Error: No analysis ID provided.");
}

$eventId = intval($_GET['id']);
if ($db_error) {
    die($db_error);
}

// Fetch analysis data
$q = "SELECT * FROM event_analyses WHERE id = $eventId";
$res = mysqli_query($conn, $q);
if (!$res || mysqli_num_rows($res) === 0) {
    die("Analysis not found.");
}
$data = mysqli_fetch_array($res);

// Fetch products
$products = [];
$pq = "SELECT * FROM event_products WHERE event_id = $eventId";
$pres = mysqli_query($conn, $pq);
if ($pres) {
    while ($prow = mysqli_fetch_array($pres)) {
        $products[] = $prow;
    }
}

// --- Initialize FPDF ---
class BlueprintPDF extends FPDF {
    // Page header
    function Header() {
        // Logo / Title area
        $this->SetFont('Arial','B',20);
        $this->SetTextColor(59, 130, 246); // Blue branding
        $this->Cell(0,10,'BLUEPRINT PRO - Financial Intelligence',0,1,'L');
        
        $this->SetFont('Arial','',10);
        $this->SetTextColor(100, 116, 139);
        $this->Cell(0,6,'Decision Validation & Financial Breakdown Report',0,1,'L');
        $this->Ln(4);
        
        // Draw a line
        $this->SetDrawColor(226, 232, 240);
        $this->Line(10, $this->GetY(), 200, $this->GetY());
        $this->Ln(6);
    }

    // Page footer
    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial','I',8);
        $this->SetTextColor(148, 163, 184);
        $this->Cell(0,10,'Page '.$this->PageNo().' - Generated by Blueprint Pro System',0,0,'C');
    }
    
    // Helper to draw a KPI box
    function KPIBox($x, $y, $w, $h, $label, $value, $subtext = '', $isPositive = true) {
        $this->SetXY($x, $y);
        
        // Box background & border
        $this->SetFillColor(248, 250, 252);
        $this->SetDrawColor(226, 232, 240);
        $this->Rect($x, $y, $w, $h, 'DF');
        
        // Label
        $this->SetXY($x + 4, $y + 4);
        $this->SetFont('Arial','B',9);
        $this->SetTextColor(71, 85, 105);
        $this->Cell($w - 8, 5, $label, 0, 1, 'C');
        
        // Value
        $this->SetXY($x + 2, $y + 11);
        $this->SetFont('Arial','B',14);
        if ($label == 'Projected Profit/Loss' || $label == 'Variance') {
            if ($isPositive) {
                $this->SetTextColor(16, 185, 129); // Green
            } else {
                $this->SetTextColor(239, 68, 68); // Red
            }
        } else {
            $this->SetTextColor(30, 41, 59); // Dark
        }
        $this->Cell($w - 4, 8, $value, 0, 1, 'C');
        
        // Subtext
        if ($subtext) {
            $this->SetXY($x + 2, $y + 20);
            $this->SetFont('Arial','',8);
            $this->SetTextColor(148, 163, 184);
            $this->Cell($w - 4, 4, $subtext, 0, 1, 'C');
        }
    }
}

$pdf = new BlueprintPDF();
$pdf->AddPage();
$pdf->SetAutoPageBreak(true, 15);

// ==========================================
// 1. EVENT INFO & VERDICT
// ==========================================
$pdf->SetFont('Arial','B',16);
$pdf->SetTextColor(15, 23, 42); // Very dark slate
$pdf->Cell(130, 8, iconv('UTF-8', 'windows-1252', $data['event_name']), 0, 0, 'L');

$pdf->SetFont('Arial','B',12);
if ($data['risk_level'] === 'HIGH') {
    $pdf->SetTextColor(239, 68, 68);
} else if ($data['risk_level'] === 'LOW') {
    $pdf->SetTextColor(16, 185, 129);
} else {
    $pdf->SetTextColor(245, 158, 11); // Yellow
}
$pdf->Cell(60, 8, strtoupper($data['risk_level']) . ' RISK', 0, 1, 'R');

$pdf->SetFont('Arial','I',10);
$pdf->SetTextColor(100, 116, 139);
$pdf->Cell(0, 6, $data['event_days'] . ' Days | Base Conv: ' . number_format($data['conversion_rate'], 1) . '% | Tax: ' . number_format($data['tax_rate'],1).'% ('.($data['is_tax_inclusive']?'Inc':'Exc').')', 0, 1, 'L');
$pdf->Ln(6);

// Verdict Banner
$pdf->SetFillColor(241, 245, 249);
$pdf->Rect(10, $pdf->GetY(), 190, 12, 'F');
$pdf->SetY($pdf->GetY() + 3);
$pdf->SetFont('Arial','B',11);
$pdf->SetTextColor(30, 41, 59);
$pdf->Cell(190, 6, "VERDICT:  " . iconv('UTF-8', 'windows-1252', $data['verdict']), 0, 1, 'C');
$pdf->Ln(8);

// ==========================================
// 2. PRIMARY KPIs
// ==========================================
$startY = $pdf->GetY();
$boxWidth = 60;
$margin = 5;

// Box 1: BEP
$pdf->KPIBox(10, $startY, $boxWidth, 26, 'Break-Even Point', number_format($data['break_even_units']), 'units to sell');

// Box 2: Profit
$isProfitable = ($data['projected_profit'] >= 0);
$pref = $isProfitable ? '+' : '';
$pdf->KPIBox(10 + $boxWidth + $margin, $startY, $boxWidth, 26, 'Projected Profit/Loss', $pref . 'RM ' . number_format($data['projected_profit'], 2), 'estimated', $isProfitable);

// Box 3: Total Sales
$pdf->KPIBox(10 + ($boxWidth + $margin)*2, $startY, $boxWidth, 26, 'Est. Revenue', 'RM ' . number_format($data['estimated_revenue'], 2), 'total estimated sales');

$pdf->Ln(34);

// ==========================================
// 3. FINANCIAL BREAKDOWN
// ==========================================
$pdf->SetFont('Arial','B',12);
$pdf->SetTextColor(15, 23, 42);
$pdf->Cell(0, 8, 'Financial Breakdown', 0, 1, 'L');
$pdf->SetDrawColor(226, 232, 240);
$pdf->Line(10, $pdf->GetY(), 60, $pdf->GetY());
$pdf->Ln(4);

$pdf->SetFont('Arial','',10);
$pdf->SetTextColor(71, 85, 105);

function printFinRow($pdf, $label, $val, $isBold = false) {
    if ($isBold) {
        $pdf->SetFont('Arial','B',10);
        $pdf->SetTextColor(30, 41, 59);
    } else {
        $pdf->SetFont('Arial','',10);
        $pdf->SetTextColor(71, 85, 105);
    }
    $pdf->Cell(95, 6, $label, 0, 0, 'L');
    $pdf->Cell(95, 6, 'RM ' . number_format($val, 2), 0, 1, 'R');
}

printFinRow($pdf, 'Booth Rental', $data['booth_rental']);
printFinRow($pdf, 'Transport / Gas', $data['transport_cost']);
printFinRow($pdf, 'Marketing Materials', $data['marketing_cost']);
// Labor string
$laborStr = "Labor ({$data['num_staff']} staff x RM {$data['hourly_wage']}/hr)";
printFinRow($pdf, $laborStr, $data['total_fixed_costs'] - $data['booth_rental'] - $data['transport_cost'] - $data['marketing_cost']);

$pdf->Ln(2);
$pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
$pdf->Ln(2);
printFinRow($pdf, 'TOTAL FIXED COSTS', $data['total_fixed_costs'], true);

$pdf->Ln(4);
printFinRow($pdf, 'Total COGS (Inc. ' . number_format($data['expected_wastage_pct'], 1) . '% wastage)', $data['total_cogs']);
printFinRow($pdf, 'Estimated Total Revenue', $data['estimated_revenue']);

$pdf->Ln(2);
$pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
$pdf->Ln(2);

// Check if actuals exist and display Variance
$isCompleted = ($data['status'] === 'completed');
if ($isCompleted) {
    $actQ = "SELECT * FROM event_actuals WHERE event_id = $eventId";
    $actRes = mysqli_query($conn, $actQ);
    if ($actRes && mysqli_num_rows($actRes) > 0) {
        $actData = mysqli_fetch_array($actRes);
        $actProfit = $actData['actual_profit'];
        $variance = $actProfit - $data['projected_profit'];
        
        printFinRow($pdf, 'PROJECTED PROFIT/LOSS', $data['projected_profit'], true);
        
        $pdf->SetFont('Arial','B',10);
        $pdf->SetTextColor(139, 92, 246); // Purple
        $pdf->Cell(95, 8, 'ACTUAL PROFIT/LOSS (COMPLETED)', 0, 0, 'L');
        $pdf->Cell(95, 8, 'RM ' . number_format($actProfit, 2), 0, 1, 'R');
        
        $pdf->SetFont('Arial','',10);
        $pdf->SetTextColor(71, 85, 105);
        $pdf->Cell(95, 6, 'Variance (Actual - Forecast)', 0, 0, 'L');
        if ($variance >= 0) $pdf->SetTextColor(16, 185, 129);
        else $pdf->SetTextColor(239, 68, 68);
        $pdf->Cell(95, 6, ($variance >= 0 ? '+' : '') . 'RM ' . number_format($variance, 2), 0, 1, 'R');
    }
} else {
    printFinRow($pdf, 'PROJECTED PROFIT/LOSS', $data['projected_profit'], true);
}

// ==========================================
// 4. PRODUCT MIX
// ==========================================
$pdf->Ln(10);
$pdf->SetFont('Arial','B',12);
$pdf->SetTextColor(15, 23, 42);
$pdf->Cell(0, 8, 'Product Strategy', 0, 1, 'L');
$pdf->SetDrawColor(226, 232, 240);
$pdf->Line(10, $pdf->GetY(), 50, $pdf->GetY());
$pdf->Ln(4);

// Table Header
$pdf->SetFillColor(241, 245, 249);
$pdf->SetFont('Arial','B',9);
$pdf->SetTextColor(30, 41, 59);
$pdf->Cell(55, 8, 'Product Name', 1, 0, 'L', true);
$pdf->Cell(25, 8, 'Price', 1, 0, 'R', true);
$pdf->Cell(25, 8, 'COGS', 1, 0, 'R', true);
$pdf->Cell(25, 8, 'Margin', 1, 0, 'R', true);
$pdf->Cell(30, 8, 'Est. Units', 1, 0, 'R', true);
$pdf->Cell(30, 8, 'Est. Revenue', 1, 1, 'R', true);

$pdf->SetFont('Arial','',9);
foreach($products as $p) {
    if (iconv_strlen($p['product_name']) > 25) {
        $pName = iconv_substr($p['product_name'], 0, 22) . '...';
    } else {
        $pName = $p['product_name'];
    }
    
    $pdf->Cell(55, 8, iconv('UTF-8', 'windows-1252', $pName), 1, 0, 'L');
    $pdf->Cell(25, 8, number_format($p['selling_price'], 2), 1, 0, 'R');
    $pdf->Cell(25, 8, number_format($p['cogs_per_unit'], 2), 1, 0, 'R');
    $pdf->Cell(25, 8, number_format($p['gross_margin'], 2), 1, 0, 'R');
    $pdf->Cell(30, 8, number_format($p['estimated_units']), 1, 0, 'R');
    $pdf->Cell(30, 8, number_format($p['estimated_revenue'], 2), 1, 1, 'R');
}

// ==========================================
// 5. REALITY CHECK
// ==========================================
$pdf->Ln(8);
$pdf->SetFillColor(248, 250, 252);
$pdf->Rect(10, $pdf->GetY(), 190, 25, 'F');
$pdf->SetXY(15, $pdf->GetY() + 5);
$pdf->SetFont('Arial','B',10);
$pdf->SetTextColor(30, 41, 59);
$pdf->Cell(0, 6, "Reality Check Focus:", 0, 1, 'L');

$pdf->SetX(15);
$pdf->SetFont('Arial','',9);
$pdf->SetTextColor(71, 85, 105);
$pdf->Cell(80, 5, "Required Conversion to Break Even:", 0, 0, 'L');
$pdf->SetFont('Arial','B',9);
$pdf->Cell(20, 5, number_format($data['required_conv_rate'], 2) . '%', 0, 1, 'R');

$pdf->SetX(15);
$pdf->SetFont('Arial','',9);
$pdf->Cell(80, 5, "Average Weighted Margin:", 0, 0, 'L');
$pdf->SetFont('Arial','B',9);
$pdf->Cell(20, 5, 'RM ' . number_format($data['weighted_margin'], 2), 0, 1, 'R');

$pdf->Output('I', 'Blueprint_Pro_Execution_Report_'.$eventId.'.pdf');
?>
